package ch.ohne.dachschaden.client;

import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;
import ch.ohne.dachschaden.client.adminCodes.AdminCodes;
import ch.ohne.dachschaden.client.adminCodes.AdminCodesRepository;
import org.springframework.beans.factory.annotation.Autowired;

@Route("data")
public class DataView extends VerticalLayout {

    private final AdminCodesRepository adminCodesRepository;

    @Autowired
    public DataView(AdminCodesRepository adminCodesRepository) {
        this.adminCodesRepository = adminCodesRepository;

        Grid<AdminCodes> grid = new Grid<>(AdminCodes.class);
        grid.setItems(adminCodesRepository.findAll());

        // Optional: hide the autogenerated id field if you want
        // grid.removeColumnByKey("id");

        add(grid);
    }
}
