
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ohneDachschadenDB
    command: -c 'max_connections=2000'
    network_mode: bridge
    ports:
      - 5432:5432
    volumes:
      - ~/apps/ohneDachschadenDB:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=UDM